# Generated by Django 5.2.15 on 2026-06-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifiscan',
            old_name='timestamp',
            new_name='scanned_at',
        ),
        migrations.AddField(
            model_name='wifiscan',
            name='band',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='wifiscan',
            name='bssid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wifiscan',
            name='channel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wifiscan',
            name='security',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wifiscan',
            name='signal',
            field=models.IntegerField(default=0),
        ),
    ]
