# Generated by Django 5.2.15 on 2026-09-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_rename_timestamp_wifiscan_scanned_at_wifiscan_band_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('server', 'Server'), ('router', 'Router'), ('switch', 'Switch'), ('ap', 'Access Point'), ('workstation', 'Workstation')], default='workstation', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='os_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
